import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Header from '../components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter.className} flex h-screen flex-col bg-green-100`}
      >
        <Header />
        <div className="flex flex-1">{children}</div>
      </body>
    </html>
  )
}
